FROM ghcr.io/eodcgmbh/openeo-argoworkflows:executor-2025.5.1
USER root

RUN apt-get update && apt-get install -y libexpat1 && rm -rf /var/lib/apt/lists/*
# Fix: Replace io.py with the fixed version
COPY io_fixed.py /opt/openeo_argoworkflows_executor/extra_processes/process_implementations/io.py